### ISSUE TITLE
Request: latest TF built with CUDA 9.0

### ISSUE THREAD

**Issue by yaroslavvb** [yaroslavvb/tensorflow-community-wheels#42]
For the latest p3 machines

**Comment by damonmaria** [comment]
I tried building myself but got stuck with:
```
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/fft2d/BUILD.bazel:21:1: C++ compilation of rule '@fft2d//:fft2d' failed (Exit 2)
python: can't open file 'external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc': [Errno 2] No such file or directory
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

And none of the Interwebs answers got me any futher.

**Comment by vellamike** [comment]
I tried building TF from source and got stuck on:

```
WARNING: Output base '/nfs/vnx-home/mvella/.cache/bazel/_bazel_mvella/70419d231f3d5732af8c1ff7fc23051d' is on NFS. This may lead to surprising failures and undetermined behavior.
Problem with java installation: couldn't find/access rt.jar in /usr/lib/jvm/java-9-openjdk-amd64
Traceback (most recent call last):
  File "configure.py", line 1052, in <module>
    main()
  File "configure.py", line 984, in main
    check_bazel_version('0.5.4')
  File "configure.py", line 444, in check_bazel_version
    curr_version = run_shell(['bazel', '--batch', 'version'])
  File "configure.py", line 141, in run_shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bazel', '--batch', 'version']' returned non-zero exit status 1
```

**Comment by vellamike** [comment]
OK I solved that issue by downgrading my JDK, now trying to continue compiling from source

**Comment by vellamike** [comment]
Compiled from source but didn't use the recipe outlined here: https://github.com/yaroslavvb/tensorflow-community-wheels instead I roughly followed these instructions: https://gist.github.com/kmhofmann/e368a2ebba05f807fa1a90b3bf9a1e03
